// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAccDataSource
func TestAccDataSourceIseNetworkAccessDictionaryAttribute(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_dictionary_attribute.test", "dictionary_name", "CustomDict"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_dictionary_attribute.test", "name", "Custom-Attr"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_dictionary_attribute.test", "description", "My custom dictionary attribute"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_dictionary_attribute.test", "data_type", "STRING"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_dictionary_attribute.test", "direction_type", "BOTH"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_dictionary_attribute.test", "internal_name", "Custom-Attr"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_dictionary_attribute.test", "allowed_values.0.key", "key1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_dictionary_attribute.test", "allowed_values.0.value", "value1"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIseNetworkAccessDictionaryAttributeConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

//template:end testAccDataSource

//template:begin testPrerequisites
//template:end testPrerequisites

//template:begin testAccDataSourceConfig
func testAccDataSourceIseNetworkAccessDictionaryAttributeConfig() string {
	config := `resource "ise_network_access_dictionary_attribute" "test" {` + "\n"
	config += `	dictionary_name = "CustomDict"` + "\n"
	config += `	name = "Custom-Attr"` + "\n"
	config += `	description = "My custom dictionary attribute"` + "\n"
	config += `	data_type = "STRING"` + "\n"
	config += `	direction_type = "BOTH"` + "\n"
	config += `	internal_name = "Custom-Attr"` + "\n"
	config += `	allowed_values = [{` + "\n"
	config += `	  key = "key1"` + "\n"
	config += `	  value = "value1"` + "\n"
	config += `	}]` + "\n"
	config += `}` + "\n"

	config += `
		data "ise_network_access_dictionary_attribute" "test" {
			id = ise_network_access_dictionary_attribute.test.id
			dictionary_name = "CustomDict"
		}
	`
	return config
}

//template:end testAccDataSourceConfig
