// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAccDataSource
func TestAccDataSourceIseTrustSecEgressMatrixCell(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_trustsec_egress_matrix_cell.test", "description", "EgressMatrixCell Description"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_trustsec_egress_matrix_cell.test", "default_rule", "NONE"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_trustsec_egress_matrix_cell.test", "matrix_cell_status", "ENABLED"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIseTrustSecEgressMatrixCellPrerequisitesConfig + testAccDataSourceIseTrustSecEgressMatrixCellConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

//template:end testAccDataSource

//template:begin testPrerequisites
const testAccDataSourceIseTrustSecEgressMatrixCellPrerequisitesConfig = `
resource "ise_trustsec_security_group" "test" {
  name              = "SGT1234"
  description       = "My SGT"
  value             = 1234
  propogate_to_apic = true
  is_read_only      = false
}
resource "ise_trustsec_security_group_acl" "test" {
  name        = "ACL1"
  description = "SG ACL 1"
  acl_content = "Permit IP"
  ip_version  = "IPV4"
  read_only   = false
}

`

//template:end testPrerequisites

//template:begin testAccDataSourceConfig
func testAccDataSourceIseTrustSecEgressMatrixCellConfig() string {
	config := `resource "ise_trustsec_egress_matrix_cell" "test" {` + "\n"
	config += `	description = "EgressMatrixCell Description"` + "\n"
	config += `	default_rule = "NONE"` + "\n"
	config += `	matrix_cell_status = "ENABLED"` + "\n"
	config += `	sgacls = [ise_trustsec_security_group_acl.test.id]` + "\n"
	config += `	source_sgt_id = ise_trustsec_security_group.test.id` + "\n"
	config += `	destination_sgt_id = ise_trustsec_security_group.test.id` + "\n"
	config += `}` + "\n"

	config += `
		data "ise_trustsec_egress_matrix_cell" "test" {
			id = ise_trustsec_egress_matrix_cell.test.id
		}
	`
	return config
}

//template:end testAccDataSourceConfig
