// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceIseRepository(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_repository.test", "name", "repo1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_repository.test", "protocol", "SFTP"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_repository.test", "path", "/dir"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_repository.test", "server_name", "server1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_repository.test", "user_name", "user1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_repository.test", "enable_pki", "false"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIseRepositoryConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

func testAccDataSourceIseRepositoryConfig() string {
	config := `resource "ise_repository" "test" {` + "\n"
	config += `	name = "repo1"` + "\n"
	config += `	protocol = "SFTP"` + "\n"
	config += `	path = "/dir"` + "\n"
	config += `	server_name = "server1"` + "\n"
	config += `	user_name = "user1"` + "\n"
	config += `	password = "cisco123"` + "\n"
	config += `	enable_pki = false` + "\n"
	config += `}` + "\n"

	config += `
		data "ise_repository" "test" {
			id = ise_repository.test.id
		}
	`
	return config
}
