// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceIseNetworkAccessPolicySet(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "name", "PolicySet1"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "description", "My description"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "is_proxy", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "rank", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "service_name", "Default Network Access"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "condition_type", "ConditionAttributes"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "condition_is_negate", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "condition_attribute_name", "Location"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "condition_attribute_value", "All Locations"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "condition_dictionary_name", "DEVICE"))
	checks = append(checks, resource.TestCheckResourceAttr("data.ise_network_access_policy_set.test", "condition_operator", "equals"))
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceIseNetworkAccessPolicySetConfig(),
				Check:  resource.ComposeTestCheckFunc(checks...),
			},
		},
	})
}

func testAccDataSourceIseNetworkAccessPolicySetConfig() string {
	config := `resource "ise_network_access_policy_set" "test" {` + "\n"
	config += `	name = "PolicySet1"` + "\n"
	config += `	description = "My description"` + "\n"
	config += `	is_proxy = false` + "\n"
	config += `	rank = 0` + "\n"
	config += `	service_name = "Default Network Access"` + "\n"
	config += `	state = "enabled"` + "\n"
	config += `	condition_type = "ConditionAttributes"` + "\n"
	config += `	condition_is_negate = false` + "\n"
	config += `	condition_attribute_name = "Location"` + "\n"
	config += `	condition_attribute_value = "All Locations"` + "\n"
	config += `	condition_dictionary_name = "DEVICE"` + "\n"
	config += `	condition_operator = "equals"` + "\n"
	config += `}` + "\n"

	config += `
		data "ise_network_access_policy_set" "test" {
			id = ise_network_access_policy_set.test.id
		}
	`
	return config
}
