// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type SXPDomainFilter struct {
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	Subnet      types.String `tfsdk:"subnet"`
	Sgt         types.String `tfsdk:"sgt"`
	Vn          types.String `tfsdk:"vn"`
	Domains     types.String `tfsdk:"domains"`
}

//template:end types

//template:begin getPath
func (data SXPDomainFilter) getPath() string {
	return "/ers/config/filterpolicy"
}

//template:end getPath

//template:begin getPathDelete

//template:end getPathDelete

//template:begin toBody
func (data SXPDomainFilter) toBody(ctx context.Context, state SXPDomainFilter) string {
	body := ""
	if !data.Name.IsNull() {
		body, _ = sjson.Set(body, "ERSFilterPolicy.name", data.Name.ValueString())
	}
	if !data.Description.IsNull() {
		body, _ = sjson.Set(body, "ERSFilterPolicy.description", data.Description.ValueString())
	}
	if !data.Subnet.IsNull() {
		body, _ = sjson.Set(body, "ERSFilterPolicy.subnet", data.Subnet.ValueString())
	}
	if !data.Sgt.IsNull() {
		body, _ = sjson.Set(body, "ERSFilterPolicy.sgt", data.Sgt.ValueString())
	}
	if !data.Vn.IsNull() {
		body, _ = sjson.Set(body, "ERSFilterPolicy.vn", data.Vn.ValueString())
	}
	if !data.Domains.IsNull() {
		body, _ = sjson.Set(body, "ERSFilterPolicy.domains", data.Domains.ValueString())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *SXPDomainFilter) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("ERSFilterPolicy.name"); value.Exists() && value.Type != gjson.Null {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("ERSFilterPolicy.description"); value.Exists() && value.Type != gjson.Null {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("ERSFilterPolicy.subnet"); value.Exists() && value.Type != gjson.Null {
		data.Subnet = types.StringValue(value.String())
	} else {
		data.Subnet = types.StringNull()
	}
	if value := res.Get("ERSFilterPolicy.vn"); value.Exists() && value.Type != gjson.Null {
		data.Vn = types.StringValue(value.String())
	} else {
		data.Vn = types.StringNull()
	}
	if value := res.Get("ERSFilterPolicy.domains"); value.Exists() && value.Type != gjson.Null {
		data.Domains = types.StringValue(value.String())
	} else {
		data.Domains = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *SXPDomainFilter) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("ERSFilterPolicy.name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("ERSFilterPolicy.description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("ERSFilterPolicy.subnet"); value.Exists() && !data.Subnet.IsNull() {
		data.Subnet = types.StringValue(value.String())
	} else {
		data.Subnet = types.StringNull()
	}
	if value := res.Get("ERSFilterPolicy.vn"); value.Exists() && !data.Vn.IsNull() {
		data.Vn = types.StringValue(value.String())
	} else {
		data.Vn = types.StringNull()
	}
	if value := res.Get("ERSFilterPolicy.domains"); value.Exists() && !data.Domains.IsNull() {
		data.Domains = types.StringValue(value.String())
	} else {
		data.Domains = types.StringNull()
	}
}

//template:end updateFromBody

//template:begin isNull
func (data *SXPDomainFilter) isNull(ctx context.Context, res gjson.Result) bool {
	if !data.Name.IsNull() {
		return false
	}
	if !data.Description.IsNull() {
		return false
	}
	if !data.Subnet.IsNull() {
		return false
	}
	if !data.Sgt.IsNull() {
		return false
	}
	if !data.Vn.IsNull() {
		return false
	}
	if !data.Domains.IsNull() {
		return false
	}
	return true
}

//template:end isNull
