// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type SXPVPN struct {
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	SxpVpnName  types.String `tfsdk:"sxp_vpn_name"`
}

//template:end types

//template:begin getPath
func (data SXPVPN) getPath() string {
	return "/ers/config/sxpvpns"
}

//template:end getPath

//template:begin getPathDelete

//template:end getPathDelete

//template:begin toBody
func (data SXPVPN) toBody(ctx context.Context, state SXPVPN) string {
	body := ""
	if !data.Name.IsNull() {
		body, _ = sjson.Set(body, "ERSSxpVpn.name", data.Name.ValueString())
	}
	if !data.Description.IsNull() {
		body, _ = sjson.Set(body, "ERSSxpVpn.description", data.Description.ValueString())
	}
	if !data.SxpVpnName.IsNull() {
		body, _ = sjson.Set(body, "ERSSxpVpn.sxpVpnName", data.SxpVpnName.ValueString())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *SXPVPN) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("ERSSxpVpn.name"); value.Exists() && value.Type != gjson.Null {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("ERSSxpVpn.description"); value.Exists() && value.Type != gjson.Null {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("ERSSxpVpn.sxpVpnName"); value.Exists() && value.Type != gjson.Null {
		data.SxpVpnName = types.StringValue(value.String())
	} else {
		data.SxpVpnName = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *SXPVPN) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("ERSSxpVpn.name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("ERSSxpVpn.description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("ERSSxpVpn.sxpVpnName"); value.Exists() && !data.SxpVpnName.IsNull() {
		data.SxpVpnName = types.StringValue(value.String())
	} else {
		data.SxpVpnName = types.StringNull()
	}
}

//template:end updateFromBody

//template:begin isNull
func (data *SXPVPN) isNull(ctx context.Context, res gjson.Result) bool {
	if !data.Name.IsNull() {
		return false
	}
	if !data.Description.IsNull() {
		return false
	}
	if !data.SxpVpnName.IsNull() {
		return false
	}
	return true
}

//template:end isNull
