// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"
	"strconv"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type NetworkAccessPolicySetUpdateRanks struct {
	Id       types.String                                `tfsdk:"id"`
	Policies []NetworkAccessPolicySetUpdateRanksPolicies `tfsdk:"policies"`
}

type NetworkAccessPolicySetUpdateRanksPolicies struct {
	Id   types.String `tfsdk:"id"`
	Rank types.Int64  `tfsdk:"rank"`
}

//template:end types

//template:begin getPath
func (data NetworkAccessPolicySetUpdateRanks) getPath() string {
	return "/api/v1/policy/network-access/policy-set"
}

//template:end getPath

//template:begin getPathDelete

//template:end getPathDelete

//template:begin toBody
func (data NetworkAccessPolicySetUpdateRanks) toBody(ctx context.Context, state NetworkAccessPolicySetUpdateRanks) string {
	body := ""
	if len(data.Policies) > 0 {
		body, _ = sjson.Set(body, "policies", []interface{}{})
		for _, item := range data.Policies {
			itemBody := ""
			if !item.Id.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "", item.Id.ValueString())
			}
			if !item.Rank.IsNull() {
				itemBody, _ = sjson.Set(itemBody, "rank", item.Rank.ValueInt64())
			}
			body, _ = sjson.SetRaw(body, "policies.-1", itemBody)
		}
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *NetworkAccessPolicySetUpdateRanks) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("response.policies"); value.Exists() {
		data.Policies = make([]NetworkAccessPolicySetUpdateRanksPolicies, 0)
		value.ForEach(func(k, v gjson.Result) bool {
			item := NetworkAccessPolicySetUpdateRanksPolicies{}
			if cValue := v.Get(""); cValue.Exists() && cValue.Type != gjson.Null {
				item.Id = types.StringValue(cValue.String())
			} else {
				item.Id = types.StringNull()
			}
			if cValue := v.Get("rank"); cValue.Exists() && cValue.Type != gjson.Null {
				item.Rank = types.Int64Value(cValue.Int())
			} else {
				item.Rank = types.Int64Null()
			}
			data.Policies = append(data.Policies, item)
			return true
		})
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *NetworkAccessPolicySetUpdateRanks) updateFromBody(ctx context.Context, res gjson.Result) {
	for i := range data.Policies {
		keys := [...]string{"", "rank"}
		keyValues := [...]string{data.Policies[i].Id.ValueString(), strconv.FormatInt(data.Policies[i].Rank.ValueInt64(), 10)}

		var r gjson.Result
		res.Get("response").ForEach(
			func(_, v gjson.Result) bool {
				found := false
				for ik := range keys {
					if v.Get(keys[ik]).String() == keyValues[ik] {
						found = true
						continue
					}
					found = false
					break
				}
				if found {
					r = v
					return false
				}
				return true
			},
		)
		if value := r.Get(""); value.Exists() && !data.Policies[i].Id.IsNull() {
			data.Policies[i].Id = types.StringValue(value.String())
		} else {
			data.Policies[i].Id = types.StringNull()
		}
		if value := r.Get("rank"); value.Exists() && !data.Policies[i].Rank.IsNull() {
			data.Policies[i].Rank = types.Int64Value(value.Int())
		} else {
			data.Policies[i].Rank = types.Int64Null()
		}
	}
}

//template:end updateFromBody

//template:begin isNull
func (data *NetworkAccessPolicySetUpdateRanks) isNull(ctx context.Context, res gjson.Result) bool {
	if len(data.Policies) > 0 {
		return false
	}
	return true
}

//template:end isNull
