// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type TrustSecSecurityGroupACL struct {
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	AclContent  types.String `tfsdk:"acl_content"`
	IpVersion   types.String `tfsdk:"ip_version"`
	ReadOnly    types.Bool   `tfsdk:"read_only"`
}

//template:end types

//template:begin getPath
func (data TrustSecSecurityGroupACL) getPath() string {
	return "/ers/config/sgacl"
}

//template:end getPath

//template:begin toBody
func (data TrustSecSecurityGroupACL) toBody(ctx context.Context, state TrustSecSecurityGroupACL) string {
	body := ""
	if !data.Name.IsNull() {
		body, _ = sjson.Set(body, "Sgacl.name", data.Name.ValueString())
	}
	if !data.Description.IsNull() {
		body, _ = sjson.Set(body, "Sgacl.description", data.Description.ValueString())
	}
	if !data.AclContent.IsNull() {
		body, _ = sjson.Set(body, "Sgacl.aclcontent", data.AclContent.ValueString())
	}
	if !data.IpVersion.IsNull() {
		body, _ = sjson.Set(body, "Sgacl.ipVersion", data.IpVersion.ValueString())
	}
	if !data.ReadOnly.IsNull() {
		body, _ = sjson.Set(body, "Sgacl.readOnly", data.ReadOnly.ValueBool())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *TrustSecSecurityGroupACL) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("Sgacl.name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("Sgacl.description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("Sgacl.aclcontent"); value.Exists() {
		data.AclContent = types.StringValue(value.String())
	} else {
		data.AclContent = types.StringNull()
	}
	if value := res.Get("Sgacl.ipVersion"); value.Exists() {
		data.IpVersion = types.StringValue(value.String())
	} else {
		data.IpVersion = types.StringValue("IP_AGNOSTIC")
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *TrustSecSecurityGroupACL) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("Sgacl.name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("Sgacl.description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("Sgacl.aclcontent"); value.Exists() && !data.AclContent.IsNull() {
		data.AclContent = types.StringValue(value.String())
	} else {
		data.AclContent = types.StringNull()
	}
	if value := res.Get("Sgacl.ipVersion"); value.Exists() && !data.IpVersion.IsNull() {
		data.IpVersion = types.StringValue(value.String())
	} else if data.IpVersion.ValueString() != "IP_AGNOSTIC" {
		data.IpVersion = types.StringNull()
	}
}

//template:end updateFromBody

//template:begin isNull
func (data *TrustSecSecurityGroupACL) isNull(ctx context.Context, res gjson.Result) bool {
	if !data.Name.IsNull() {
		return false
	}
	if !data.Description.IsNull() {
		return false
	}
	if !data.AclContent.IsNull() {
		return false
	}
	if !data.IpVersion.IsNull() {
		return false
	}
	if !data.ReadOnly.IsNull() {
		return false
	}
	return true
}

//template:end isNull
