// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

//template:end imports

//template:begin types
type EndpointCustomAttribute struct {
	Id            types.String `tfsdk:"id"`
	AttributeName types.String `tfsdk:"attribute_name"`
	AttributeType types.String `tfsdk:"attribute_type"`
}

//template:end types

//template:begin getPath
func (data EndpointCustomAttribute) getPath() string {
	return "/api/v1/endpoint-custom-attribute"
}

//template:end getPath

//template:begin getPathDelete

//template:end getPathDelete

//template:begin toBody
func (data EndpointCustomAttribute) toBody(ctx context.Context, state EndpointCustomAttribute) string {
	body := ""
	if !data.AttributeName.IsNull() {
		body, _ = sjson.Set(body, "attributeName", data.AttributeName.ValueString())
	}
	if !data.AttributeType.IsNull() {
		body, _ = sjson.Set(body, "attributeType", data.AttributeType.ValueString())
	}
	return body
}

//template:end toBody

//template:begin fromBody
func (data *EndpointCustomAttribute) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("attributeName"); value.Exists() && value.Type != gjson.Null {
		data.AttributeName = types.StringValue(value.String())
	} else {
		data.AttributeName = types.StringNull()
	}
	if value := res.Get("attributeType"); value.Exists() && value.Type != gjson.Null {
		data.AttributeType = types.StringValue(value.String())
	} else {
		data.AttributeType = types.StringNull()
	}
}

//template:end fromBody

//template:begin updateFromBody
func (data *EndpointCustomAttribute) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("attributeName"); value.Exists() && !data.AttributeName.IsNull() {
		data.AttributeName = types.StringValue(value.String())
	} else {
		data.AttributeName = types.StringNull()
	}
	if value := res.Get("attributeType"); value.Exists() && !data.AttributeType.IsNull() {
		data.AttributeType = types.StringValue(value.String())
	} else {
		data.AttributeType = types.StringNull()
	}
}

//template:end updateFromBody

//template:begin isNull
func (data *EndpointCustomAttribute) isNull(ctx context.Context, res gjson.Result) bool {
	if !data.AttributeName.IsNull() {
		return false
	}
	if !data.AttributeType.IsNull() {
		return false
	}
	return true
}

//template:end isNull
