// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

type UserIdentityGroup struct {
	Id                        types.String `tfsdk:"id"`
	Name                      types.String `tfsdk:"name"`
	Description               types.String `tfsdk:"description"`
	ParentUserIdentityGroupId types.String `tfsdk:"parent_user_identity_group_id"`
}

func (data UserIdentityGroup) toBody(ctx context.Context, state UserIdentityGroup) string {
	body := ""
	if !data.Name.IsNull() {
		body, _ = sjson.Set(body, "IdentityGroup.name", data.Name.ValueString())
	}
	if !data.Description.IsNull() {
		body, _ = sjson.Set(body, "IdentityGroup.description", data.Description.ValueString())
	}
	if !data.ParentUserIdentityGroupId.IsNull() {
		body, _ = sjson.Set(body, "IdentityGroup.parentId", data.ParentUserIdentityGroupId.ValueString())
	}
	return body
}

func (data *UserIdentityGroup) fromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("IdentityGroup.name"); value.Exists() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("IdentityGroup.description"); value.Exists() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("IdentityGroup.parentId"); value.Exists() {
		data.ParentUserIdentityGroupId = types.StringValue(value.String())
	} else {
		data.ParentUserIdentityGroupId = types.StringNull()
	}
}

func (data *UserIdentityGroup) updateFromBody(ctx context.Context, res gjson.Result) {
	if value := res.Get("IdentityGroup.name"); value.Exists() && !data.Name.IsNull() {
		data.Name = types.StringValue(value.String())
	} else {
		data.Name = types.StringNull()
	}
	if value := res.Get("IdentityGroup.description"); value.Exists() && !data.Description.IsNull() {
		data.Description = types.StringValue(value.String())
	} else {
		data.Description = types.StringNull()
	}
	if value := res.Get("IdentityGroup.parentId"); value.Exists() && !data.ParentUserIdentityGroupId.IsNull() {
		data.ParentUserIdentityGroupId = types.StringValue(value.String())
	} else {
		data.ParentUserIdentityGroupId = types.StringNull()
	}
}
