// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAcc
func TestAccIseTrustSecEgressMatrixCellDefault(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("ise_trustsec_egress_matrix_cell_default.test", "description", "Default egress rule"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_trustsec_egress_matrix_cell_default.test", "default_rule", "PERMIT_IP"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_trustsec_egress_matrix_cell_default.test", "matrix_cell_status", "ENABLED"))

	var steps []resource.TestStep
	steps = append(steps, resource.TestStep{
		Config: testAccIseTrustSecEgressMatrixCellDefaultConfig_all(),
		Check:  resource.ComposeTestCheckFunc(checks...),
	})
	steps = append(steps, resource.TestStep{
		ResourceName: "ise_trustsec_egress_matrix_cell_default.test",
		ImportState:  true,
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps:                    steps,
	})
}

//template:end testAcc

//template:begin testPrerequisites
//template:end testPrerequisites

//template:begin testAccConfigMinimal
func testAccIseTrustSecEgressMatrixCellDefaultConfig_minimum() string {
	config := `resource "ise_trustsec_egress_matrix_cell_default" "test" {` + "\n"
	config += `	id = "92c1a900-8c01-11e6-996c-525400b48521"` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigMinimal

//template:begin testAccConfigAll
func testAccIseTrustSecEgressMatrixCellDefaultConfig_all() string {
	config := `resource "ise_trustsec_egress_matrix_cell_default" "test" {` + "\n"
	config += `	description = "Default egress rule"` + "\n"
	config += `	default_rule = "PERMIT_IP"` + "\n"
	config += `	matrix_cell_status = "ENABLED"` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigAll
