// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccIseNetworkAccessDictionary(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_dictionary.test", "name", "Dict1"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_dictionary.test", "description", "My description"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_dictionary.test", "version", "1.1"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_dictionary.test", "dictionary_attr_type", "ENTITY_ATTR"))

	var steps []resource.TestStep
	if os.Getenv("SKIP_MINIMUM_TEST") == "" {
		steps = append(steps, resource.TestStep{
			Config: testAccIseNetworkAccessDictionaryConfig_minimum(),
		})
	}
	steps = append(steps, resource.TestStep{
		Config: testAccIseNetworkAccessDictionaryConfig_all(),
		Check:  resource.ComposeTestCheckFunc(checks...),
	})
	steps = append(steps, resource.TestStep{
		ResourceName: "ise_network_access_dictionary.test",
		ImportState:  true,
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps:                    steps,
	})
}

func testAccIseNetworkAccessDictionaryConfig_minimum() string {
	config := `resource "ise_network_access_dictionary" "test" {` + "\n"
	config += `	name = "Dict1"` + "\n"
	config += `	version = "1.1"` + "\n"
	config += `	dictionary_attr_type = "ENTITY_ATTR"` + "\n"
	config += `}` + "\n"
	return config
}

func testAccIseNetworkAccessDictionaryConfig_all() string {
	config := `resource "ise_network_access_dictionary" "test" {` + "\n"
	config += `	name = "Dict1"` + "\n"
	config += `	description = "My description"` + "\n"
	config += `	version = "1.1"` + "\n"
	config += `	dictionary_attr_type = "ENTITY_ATTR"` + "\n"
	config += `}` + "\n"
	return config
}
