// Copyright © 2023 Cisco Systems, Inc. and its affiliates.
// All rights reserved.
//
// Licensed under the Mozilla Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://mozilla.org/MPL/2.0/
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by "gen/generator.go"; DO NOT EDIT.

package provider

//template:begin imports
import (
	"os"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

//template:end imports

//template:begin testAcc
func TestAccIseNetworkAccessAuthorizationGlobalExceptionRule(t *testing.T) {
	var checks []resource.TestCheckFunc
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "name", "Rule1"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "rank", "0"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "state", "enabled"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "condition_type", "ConditionAttributes"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "condition_is_negate", "false"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "condition_attribute_name", "Location"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "condition_attribute_value", "All Locations"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "condition_dictionary_name", "DEVICE"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "condition_operator", "equals"))
	checks = append(checks, resource.TestCheckResourceAttr("ise_network_access_authorization_global_exception_rule.test", "security_group", "BYOD"))

	var steps []resource.TestStep
	if os.Getenv("SKIP_MINIMUM_TEST") == "" {
		steps = append(steps, resource.TestStep{
			Config: testAccIseNetworkAccessAuthorizationGlobalExceptionRulePrerequisitesConfig + testAccIseNetworkAccessAuthorizationGlobalExceptionRuleConfig_minimum(),
		})
	}
	steps = append(steps, resource.TestStep{
		Config: testAccIseNetworkAccessAuthorizationGlobalExceptionRulePrerequisitesConfig + testAccIseNetworkAccessAuthorizationGlobalExceptionRuleConfig_all(),
		Check:  resource.ComposeTestCheckFunc(checks...),
	})
	steps = append(steps, resource.TestStep{
		ResourceName: "ise_network_access_authorization_global_exception_rule.test",
		ImportState:  true,
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t) },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps:                    steps,
	})
}

//template:end testAcc

//template:begin testPrerequisites
const testAccIseNetworkAccessAuthorizationGlobalExceptionRulePrerequisitesConfig = `
resource "ise_network_access_condition" "test" {
  name            = "Cond1"
  condition_type  = "LibraryConditionAttributes"
  attribute_name  = "NAS-Port-Type"
  attribute_value = "Wireless - IEEE 802.11"
  dictionary_name = "Radius"
  operator        = "equals"
}

`

//template:end testPrerequisites

//template:begin testAccConfigMinimal
func testAccIseNetworkAccessAuthorizationGlobalExceptionRuleConfig_minimum() string {
	config := `resource "ise_network_access_authorization_global_exception_rule" "test" {` + "\n"
	config += `	name = "Rule1"` + "\n"
	config += `	condition_type = "ConditionReference"` + "\n"
	config += `	condition_id = ise_network_access_condition.test.id` + "\n"
	config += `	profiles = ["PermitAccess"]` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigMinimal

//template:begin testAccConfigAll
func testAccIseNetworkAccessAuthorizationGlobalExceptionRuleConfig_all() string {
	config := `resource "ise_network_access_authorization_global_exception_rule" "test" {` + "\n"
	config += `	name = "Rule1"` + "\n"
	config += `	rank = 0` + "\n"
	config += `	state = "enabled"` + "\n"
	config += `	condition_type = "ConditionAttributes"` + "\n"
	config += `	condition_is_negate = false` + "\n"
	config += `	condition_attribute_name = "Location"` + "\n"
	config += `	condition_attribute_value = "All Locations"` + "\n"
	config += `	condition_dictionary_name = "DEVICE"` + "\n"
	config += `	condition_operator = "equals"` + "\n"
	config += `	profiles = ["PermitAccess"]` + "\n"
	config += `	security_group = "BYOD"` + "\n"
	config += `}` + "\n"
	return config
}

//template:end testAccConfigAll
